# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from respeecher.models.calibration_response import CalibrationResponse

class TestCalibrationResponse(unittest.TestCase):
    """CalibrationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CalibrationResponse:
        """Test CalibrationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CalibrationResponse`
        """
        model = CalibrationResponse()
        if include_optional:
            return CalibrationResponse(
                id = '',
                name = '',
                user_id = '',
                f0 = 56,
                algorithm = '',
                bucket = '',
                key = '',
                state = '',
                error = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                calibrated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enabled = True
            )
        else:
            return CalibrationResponse(
        )
        """

    def testCalibrationResponse(self):
        """Test CalibrationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
