# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from respeecher.models.generate_api_key200_response import GenerateApiKey200Response

class TestGenerateApiKey200Response(unittest.TestCase):
    """GenerateApiKey200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateApiKey200Response:
        """Test GenerateApiKey200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateApiKey200Response`
        """
        model = GenerateApiKey200Response()
        if include_optional:
            return GenerateApiKey200Response(
                api_key = ''
            )
        else:
            return GenerateApiKey200Response(
        )
        """

    def testGenerateApiKey200Response(self):
        """Test GenerateApiKey200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
