# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from respeecher.models.tts_voice import TTSVoice

class TestTTSVoice(unittest.TestCase):
    """TTSVoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TTSVoice:
        """Test TTSVoice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TTSVoice`
        """
        model = TTSVoice()
        if include_optional:
            return TTSVoice(
                id = '',
                visibility = '',
                name = '',
                f0 = 1.337,
                is_default = True
            )
        else:
            return TTSVoice(
        )
        """

    def testTTSVoice(self):
        """Test TTSVoice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
