# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from respeecher.models.tts_recording_request import TTSRecordingRequest

class TestTTSRecordingRequest(unittest.TestCase):
    """TTSRecordingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TTSRecordingRequest:
        """Test TTSRecordingRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TTSRecordingRequest`
        """
        model = TTSRecordingRequest()
        if include_optional:
            return TTSRecordingRequest(
                parent_folder_id = '',
                text = '',
                tts_voice_id = '',
                label = ''
            )
        else:
            return TTSRecordingRequest(
        )
        """

    def testTTSRecordingRequest(self):
        """Test TTSRecordingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
