# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from respeecher.models.get_credits200_response import GetCredits200Response

class TestGetCredits200Response(unittest.TestCase):
    """GetCredits200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCredits200Response:
        """Test GetCredits200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCredits200Response`
        """
        model = GetCredits200Response()
        if include_optional:
            return GetCredits200Response(
                credits = 56,
                initial_credits = 56
            )
        else:
            return GetCredits200Response(
        )
        """

    def testGetCredits200Response(self):
        """Test GetCredits200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
