# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from respeecher.models.project_statistics import ProjectStatistics

class TestProjectStatistics(unittest.TestCase):
    """ProjectStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectStatistics:
        """Test ProjectStatistics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectStatistics`
        """
        model = ProjectStatistics()
        if include_optional:
            return ProjectStatistics(
                project_id = '',
                time_converted = respeecher.models.project_statistics_time_converted.ProjectStatistics_time_converted(
                    total = 56, 
                    current_month = 56, ),
                conversions = respeecher.models.project_statistics_conversions.ProjectStatistics_conversions(
                    total = 56, 
                    completed = 56, 
                    in_progress = 56, 
                    failed = 56, )
            )
        else:
            return ProjectStatistics(
        )
        """

    def testProjectStatistics(self):
        """Test ProjectStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
