# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from respeecher.models.login200_response import Login200Response

class TestLogin200Response(unittest.TestCase):
    """Login200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Login200Response:
        """Test Login200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Login200Response`
        """
        model = Login200Response()
        if include_optional:
            return Login200Response(
                user = None,
                csrf_token = '',
                session_duration = 56
            )
        else:
            return Login200Response(
        )
        """

    def testLogin200Response(self):
        """Test Login200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
