# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from respeecher.models.account_statistics_conversions import AccountStatisticsConversions
from respeecher.models.account_statistics_models_inner import AccountStatisticsModelsInner
from respeecher.models.account_statistics_time_converted import AccountStatisticsTimeConverted
from typing import Optional, Set
from typing_extensions import Self

class AccountStatistics(BaseModel):
    """
    AccountStatistics
    """ # noqa: E501
    time_converted: Optional[AccountStatisticsTimeConverted] = None
    conversions: Optional[AccountStatisticsConversions] = None
    models: Optional[List[AccountStatisticsModelsInner]] = None
    __properties: ClassVar[List[str]] = ["time_converted", "conversions", "models"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of time_converted
        if self.time_converted:
            _dict['time_converted'] = self.time_converted.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conversions
        if self.conversions:
            _dict['conversions'] = self.conversions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item in self.models:
                if _item:
                    _items.append(_item.to_dict())
            _dict['models'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "time_converted": AccountStatisticsTimeConverted.from_dict(obj["time_converted"]) if obj.get("time_converted") is not None else None,
            "conversions": AccountStatisticsConversions.from_dict(obj["conversions"]) if obj.get("conversions") is not None else None,
            "models": [AccountStatisticsModelsInner.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None
        })
        return _obj


