# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CalibrationResponse(BaseModel):
    """
    CalibrationResponse
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = None
    f0: Optional[StrictInt] = None
    algorithm: Optional[StrictStr] = None
    bucket: Optional[StrictStr] = None
    key: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    error: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    calibrated_at: Optional[datetime] = None
    enabled: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "name", "user_id", "f0", "algorithm", "bucket", "key", "state", "error", "created_at", "calibrated_at", "enabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CalibrationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CalibrationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "user_id": obj.get("user_id"),
            "f0": obj.get("f0"),
            "algorithm": obj.get("algorithm"),
            "bucket": obj.get("bucket"),
            "key": obj.get("key"),
            "state": obj.get("state"),
            "error": obj.get("error"),
            "created_at": obj.get("created_at"),
            "calibrated_at": obj.get("calibrated_at"),
            "enabled": obj.get("enabled")
        })
        return _obj


