# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from respeecher.models.conversion_detail import ConversionDetail
from typing import Optional, Set
from typing_extensions import Self

class OrderRequest(BaseModel):
    """
    OrderRequest
    """ # noqa: E501
    original_id: Optional[StrictStr] = Field(default=None, description="The ID of the original recording to create a conversion from.")
    conversions: Optional[List[ConversionDetail]] = None
    calibration_id: Optional[StrictStr] = Field(default=None, description="The ID of the calibration to use, if applicable.")
    use_calibration: Optional[StrictBool] = Field(default=None, description="Whether to use a specific calibration for the conversion.")
    __properties: ClassVar[List[str]] = ["original_id", "conversions", "calibration_id", "use_calibration"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conversions (list)
        _items = []
        if self.conversions:
            for _item in self.conversions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['conversions'] = _items
        # set to None if calibration_id (nullable) is None
        # and model_fields_set contains the field
        if self.calibration_id is None and "calibration_id" in self.model_fields_set:
            _dict['calibration_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "original_id": obj.get("original_id"),
            "conversions": [ConversionDetail.from_dict(_item) for _item in obj["conversions"]] if obj.get("conversions") is not None else None,
            "calibration_id": obj.get("calibration_id"),
            "use_calibration": obj.get("use_calibration")
        })
        return _obj


